name: weatheree
description: A simple Flutter weather application using OpenWeatherMap API.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.2.0
  intl: ^0.19.0

 
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  http_mock_adapter: ^0.6.0

flutter:
  uses-material-design: true
